### ISSUE TITLE
タイーツのurl展開の際、空白部分が余計についている

### ISSUE THREAD

**Issue by yojiyama7** [ikasoba/taittsuu-plus#4]
<img width="648" alt="image" src="https://github.com/ikasoba/taittsuu-plus/assets/17645288/ae4bbeec-6f44-44cf-bba7-46bf53375b56">

(画像のタイーツ: https://taittsuu.com/users/yojiyama7/status/2148071)

引用されているタイーツの縦幅が必要以上に大きいように見えます。
縦幅をより小さくしてタイーツに対して適切になるようにできますか？

何か間違いがあれば申し訳ないです。

**Comment by ikasoba** [comment]
修正しときました！

**Comment by ikasoba** [comment]
このページの上のやつがオレンジから緑になればアップデートできるようになると思います。
https://github.com/ikasoba/taittsuu-plus/deployments/activity_log?environment=github-pages
